name: Test Workflow
on:
  push:
    branches: [main]  # 当 main 分支有推送时触发
jobs:
  job1:
    runs-on: ubuntu-latest  # 运行在 Ubuntu 环境
    steps:
      - run: pwd  
  job2:
    runs-on: ubuntu-latest  # 运行在 Ubuntu 环境
    steps:
      - run: python --version